# Jekyll Resume Theme

# Site settings
title: Raaqim Mohammed's Resume
email: resume@raaqim.me
description: This is my resume.
url: "https://raaqim.me"
baseurl: "/resume"
includes_dir: "/resume/_includes"
sass_dir: "/resume/_sass"
layouts_dir: "/resume/_layouts"
data_dir: "/resume/_data"
name: Raaqim Mohammed
job: Looking for a Job
location: Sydney, AU
languages: Python
twitter_username: TheRaildex1
github_username: raildex1
linkedin_vanity: RaaqimMohammed
email_address: resume@raaqim.me


# Build settings
markdown: kramdown
